=== tsandmann/ct-sim/config/config.dtd
<!ELEMENT ct-sim (description?, bots?)>
	<!ELEMENT description (#PCDATA)>

	<!ELEMENT bots (bot*)>
		<!ELEMENT bot (appearance*)>
			<!ATTLIST bot name CDATA #REQUIRED>


			<!ELEMENT appearance (description, (texture | color |clone))>
				<!ATTLIST appearance type CDATA #REQUIRED>
				<!ELEMENT texture (#PCDATA)>
				<!ELEMENT color (#PCDATA)>
					<!ATTLIST color type (ambient| diffuse | specular| emmissive) "ambient">
				<!ELEMENT clone (#PCDATA)>

=== tsandmann/ct-sim/config/ct-sim-contest-conductor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ct-sim SYSTEM "config.dtd">

<ct-sim>
	<description>
		Dies ist eine Konfigurationsdatei f√ºr den c't-Sim, die den Sim in
		Wettbewerbskonfiguration versetzt. Das bedeutet, dass als Judge der
		ContestJudge eingesetzt wird. Die Wettbewerbskonfig umfasst auch
		einige ContestJudge-spezifische Parameter, auf welcher Datenbank
		gearbeitet werden soll.

		Mit der Kommandozeilenoption -conf config/ct-sim-contest-judge.xml
		kann der Controller veranlasst werden, diese Datei statt der
		standardmaessigen zu verwenden. Zum einfachen Ausfuehren beider
		Varianten lassen sich in Eclipse zwei Run Configurations einrichten
		(eine mit der o.g. Option, eine ohne).
	</description>

	<parameter name="botport" value="10001"/>
	<parameter name="worlddir" value="./parcours"/>
	<parameter name="botdir" value="..\ct-Bot\Debug-W32"/>

	<!-- Uebergeht einen eventuellen "judge"-Parameter -->
	<parameter name="useContestConductor" value="true"/>

	<parameter name="contestBotTargetDir" value="tmp"/>
	<parameter name="contestBotFileNamePrefix" value="tmp-contest-bot"/>
	<parameter name="contestBotFileNameSuffix" value=".exe"/>

	<!-- URL, Username und Passwort der Datenbank, mit der die Klasse
	ctSim.view.contestConductor.ContestConductor reden soll (Format der URL
	wie es java.sql.DriverManager.getConnection() erwartet) -->
	<parameter name="contest-database-url"
		value="jdbc:mysql://localhost:3306/ctbot-contest"/>
	<parameter name="contest-database-user" value="root"/>
	<parameter name="contest-database-password" value=""/>

	<bots>
		<bot name="ctSim.model.bots.CtBotSimTest_0">
			<appearance type="normal">
				<description>Standard Aussehen des TestBots 1</description>
				<color>#FF0000</color>
			</appearance>
			<appearance type="collision">
				<description>Aussehen des TestBots 1 bei Kollision</description>
				<color>#800000</color>
			</appearance>
			<appearance type="falling">
				<description>Aussehen des TestBots 1 bei Absturz</description>
				<color>#5000FF</color>
			</appearance>
		</bot>
		<bot name="ctSim.model.bots.CtBotSimTest_1">
			<appearance type="normal">
				<description>Standard Aussehen des TestBots 2</description>
				<color>#00FF00</color>
			</appearance>
			<appearance type="collision">
				<description>Aussehen des TestBots 2 bei Kollision</description>
				<color>#008000</color>
			</appearance>
			<appearance type="falling">
				<description>Aussehen des TestBots 2 bei Absturz</description>
				<color>#0050FF</color>
			</appearance>
		</bot>

		<bot name="ctSim.model.bots.CtBotSimTcp_0">
			<appearance type="normal">
				<description>Standard Aussehen des simulierten Bots 1</description>
				<color>#800000</color>
			</appearance>
			<appearance type="collision">
				<description>Aussehen des  simulierten Bots 1 bei Kollision</description>
				<color>#8000FF</color>
			</appearance>
			<appearance type="falling">
				<description>Aussehen des  simulierten Bots 1 bei Absturz</description>
				<color>#4000FF</color>
			</appearance>
		</bot>

		<bot name="ctSim.model.bots.CtBotSimTcp_1">
			<appearance type="normal">
				<description>Standard Aussehen des  simulierten Bots 2</description>
				<color>#800000</color>
			</appearance>
			<appearance type="collision">
				<description>Aussehen des  simulierten Bots 2 bei Kollision</description>
				<color>#8000FF</color>
			</appearance>
			<appearance type="falling">
				<description>Aussehen des  simulierten Bots 2 bei Absturz</description>
				<color>#4000FF</color>
			</appearance>
		</bot>

		<bot name="default">
			<appearance type="normal">
				<description>Standard Aussehen des Standard-Bots</description>
				<color>#FF0000</color>
			</appearance>
			<appearance type="collision">
				<description>Aussehen des Standard-Bots bei Kollision</description>
				<color>#FF00FF</color>
			</appearance>
			<appearance type="falling">
				<description>Aussehen des Standard-Bots bei Absturz</description>
				<color>#5000FF</color>
			</appearance>
		</bot>
	</bots>
</ct-sim>
